name: location_map_picker
description: Pick Location From The map and search about any place in google map and get the output and it's the place name and LatLng using Google map and Geolocator
version: 0.0.9+1
homepage: https://github.com/abom-me/location_map_picker

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  google_maps_flutter: ^2.2.0
  geolocator: ^9.0.1
  geolocator_apple: ^2.2.1
  flutter_svg: ^1.1.6
  http: ^0.13.5
  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.1

  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:


